// angular/src/app/search/search.component.ts
import { Component, OnInit } from '@angular/core';
import { faSearch } from '@fortawesome/free-solid-svg-icons';
import { NgForm } from '@angular/forms';

import { Movie } from '../movie-list/movie-list.component';
import { TaskService } from '../task.service';


@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.scss']
})
export class SearchComponent implements OnInit {
  searchItem: string = '';
  faSearch = faSearch;

  movieList: Movie[];

  constructor(private taskService: TaskService) { }

  onSubmit(form: NgForm) {
    console.log(this.searchItem);
    this.taskService.getMovies(`search/movie?api_key=8c20094b9d32bd14049b323d7d8294d0&language=en-US&&include_adult=false&query=${this.searchItem}`)
      .subscribe((response: any) => {
        this.movieList = response.results;
      });
  }

  ngOnInit(): void {
  }

}

<div class="searchWrap">
  <form #searchForm="ngForm" (ngSubmit)="onSubmit(searchForm)">
    <input required type="text" [(ngModel)]="searchItem" name="searchItem" placeholder='Search' />
    <button type="submit" [disabled]="!searchForm.form.valid">
      <fa-icon [icon]="faSearch"></fa-icon>
    </button>
  </form>
</div>
<!-- turn pages functionality -->
<div class="d-flex flex-wrap justify-content-center" [ngStyle]="{'minHeight': '65vh'}">
  <div *ngFor="let movie of movieList" class="card m-2 m-lg-4">
    <a routerLink="/moviePage" fragment="{{movie.id}}" routerLinkActive="active">
      <img class="card-img-top" src="{{'http://image.tmdb.org/t/p/w300/' + movie.poster_path}}" alt="posterPath" />
      <div class="card-body">
        <h5 class="card-title">{{movie.title}}</h5>
        <div> 
          <span *ngFor="let genre of movie.genre_ids" class="badge bg-warning text-dark m-1">
            {{genre | genreName}}
          </span>
        </div>
        <div class="d-flex justify-content-around">
          <span>{{movie.release_date | date}}</span>
          <span>Rating: {{movie.vote_average}}</span>
        </div>
      </div>
    </a>
  </div>
</div>

// src/components/Search.jsx
import { useState, useEffect } from 'react';
import moment from "moment";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSearch } from '@fortawesome/free-solid-svg-icons';
import { NavLink } from "react-router-dom";


export default function Search() {

    const [data, setSearchedData] = useState(false);
    const [ready, setDelay] = useState(false);
    const [searched, handleSearch] = useState(false);
    const [genre, setGenre] = useState(false);

    // Get the Genre array to translate genre_ids 
    useEffect(() => {
        fetch('https://api.themoviedb.org/3/genre/movie/list?api_key=8c20094b9d32bd14049b323d7d8294d0&language=en-US', 
        { method: 'GET' })
            .then(response => response.json())
            .catch(e => console.warn('error getting genre:', e))
            .then(result => setGenre(result));
    }, []);

    // Get searched movies:
    useEffect(() => {
            fetch('https://api.themoviedb.org/3/search/movie?api_key=8c20094b9d32bd14049b323d7d8294d0&language=en-US&page=1&include_adult=false&query=' + searched)
                .then(response => response.json())
                .catch(e => console.warn('error getting movies:', e))
                .then(result => setSearchedData(result))
    }, [searched])

    useEffect(() => {
        setTimeout(() => {
            if (searched) {
                setDelay(true)
            }
         }, 200);
    }, [searched])

    return (<>
        <div className="searchWrap">
            <input type="text" placeholder='Search' />
            <button onClick={() => handleSearch(document.querySelector("input").value)}><FontAwesomeIcon icon={faSearch} /></button>
        </div>
        <div className="d-flex flex-wrap justify-content-center" style={{minHeight: "65vh"}}>
            {ready ?
            data.results.map((item, i) => 
            <div key={i} className="card m-2 m-lg-4"><NavLink to={{
                pathname:'/MoviePage',
                hash: `${data.results[i].id}`,
                state: {id: data.results[i].id}  
              }}>
                <img className="card-img-top" src={"http://image.tmdb.org/t/p/w300/" + item.poster_path} alt="" />
                <div className="card-body">
                    <h5 className="card-title">{item.title}</h5>
                    { genre ?
                    // Translate genre ID to genre Name
                    item.genre_ids.map((x, j) => {
                        let genreName = '';
                        for (let k = 0; k < genre.genres.length; k++) {
                            if (x === genre.genres[k].id) {
                                genreName = genre.genres[k].name;
                            }
                        }
                        return <span key={j} className="badge bg-warning text-dark m-1">{genreName}</span>
                    }) :
                    <p>Loading...</p>}
                    <div className="d-flex justify-content-around">
                        <span>{moment(item.release_date).format("Do MMM YYYY")}</span>
                        <span>Rating: {item.vote_average}</span>
                    </div>
                </div>
            </NavLink></div>):
            <div></div>}
        </div>
    </>)
}
