// angular/src/app/watch-list/watch-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Movie } from '../movie-list/movie-list.component';

@Component({
  selector: 'app-watch-list',
  templateUrl: './watch-list.component.html',
  styleUrls: ['./watch-list.component.scss']
})
export class WatchListComponent implements OnInit {

  movieList = JSON.parse(localStorage.getItem('watchList') || '[]');

  constructor() { }

  ngOnInit(): void {
  }

  removeFromWatchList(item: Movie) {
    const index = this.movieList.indexOf(item);
    this.movieList.splice(index, 1);
    localStorage.setItem('watchList', JSON.stringify(this.movieList));
  }

}

<div *ngIf="movieList.length !== 0; else emptyList" class="d-flex flex-wrap justify-content-center">
  <div *ngFor="let movie of movieList" class="m-2 m-lg-4 d-flex flex-column">
    <div class="card flex-grow-1">
      <a routerLink="/moviePage" fragment="{{movie.id}}" routerLinkActive="active">
        <img class="card-img-top" src="{{'http://image.tmdb.org/t/p/w300/' + movie.poster_path}}" alt="posterPath" />
        <div class="card-body">
          <h5 class="card-title">{{movie.title}}</h5>
          <div> 
            <span *ngFor="let genre of movie.genre_ids" class="badge bg-warning text-dark m-1">
              {{genre | genreName}}
            </span>
          </div>
          <div class="d-flex justify-content-around">
            <span>{{movie.release_date | date}}</span>
            <span>Rating: {{movie.vote_average}}</span>
          </div>
        </div>
      </a>
    </div>
    <button class="btn btn-danger mt-1" (click)="removeFromWatchList(movie)">
      Remove from Watch List
    </button>
  </div>
</div>
<ng-template #emptyList>
  <p [ngStyle]="{'height': '30vh'}">There are no movies in your watchlist.</p>
</ng-template>

// React/src/components/WatchList.jsx
import { useState, useEffect } from 'react';
import { NavLink } from "react-router-dom";
import moment from "moment";

export default function WatchList() {
    
    const [data, setData] = useState(false);
    const [emptyList, setListStatus] = useState(true);
    const [dataLength, setLength] = useState(false);

    const currentStorage = JSON.parse(localStorage.getItem('watchList'));
    

    // Get movies from local storage
    useEffect(() => {
        // check if localStorage was used:
        if (localStorage.getItem('watchList')) {
            setData(JSON.parse(localStorage.getItem('watchList')));
            setListStatus(false);
        }
    }, []);

    useEffect(() => {
        setData(currentStorage);
    }, [dataLength]);

    function removeFromWatchList(item) {
        const classes = item.className.split(" ")
        currentStorage.splice(classes[0], 1);
        // check if localStorage was cleared:
        if (currentStorage.length === 0) {
            setListStatus(true);
        }
        localStorage.setItem('watchList', JSON.stringify(currentStorage));
        setLength(currentStorage.length);
    }

    return (
        <div className="d-flex flex-wrap justify-content-center">
            {emptyList ?
            <p>Your watch list is empty.</p> :
            data ?
            data.map((item, i) => <div className="m-2 m-lg-4">
            <div key={i} className="card"><NavLink to={{
                pathname:'/MoviePage',
                hash: `${data[i].id}`,
                state: {id: data[i].id}  
              }}>
                <img className="card-img-top" src={"http://image.tmdb.org/t/p/w300/" + item.poster_path} alt="" />
                <div className="card-body">
                    <h5 className="card-title">{item.title}</h5>
                    { item.genres.map((x, j) => {
                        return <span key={j} className="badge bg-warning text-dark m-1">{x.name}</span>
                    })}
                    <div className="d-flex justify-content-around">
                        <span>{moment(item.release_date).format("Do MMM YYYY")}</span>
                        <span>Rating: {item.vote_average}</span>
                    </div>
                </div>
            </NavLink></div>
            <button className={i + " btn btn-danger"} onClick={(e) => removeFromWatchList(e.target)}>Remove from watch list</button>
            </div>):
            <div>Loading...</div>}
        </div>
    )
}
